### ISSUE TITLE
I'm very interested in this project

### ISSUE THREAD

**Issue by RodolfoSilva** [alex-min/live_view_native_flutter_ui#1]
I've developed my own personal LiveView(LiveJson), but is more painful to maintain 😂. Do you have any roadmap for this extension, how can I help with the project. 

Right now, my project is using Mirai and phoenix_wings

**Comment by alex-min** [comment]
Hey, thanks for the interest! 

No I don't have any roadmap to share, it's a personal project so I work on it when I have some time :)

Right now the project is on hold until the end of the month and I'll continue it then

The best roadmap I have is the "What is missing" paragraph here : https://github.com/alex-min/live_view_native_flutter_client
